//
// Created by vahan on 6/18/18.
//

#ifndef SERVER_SIDE_PLATFORM_ON_C_CPP_MAIN_SERVER_H
#define SERVER_SIDE_PLATFORM_ON_C_CPP_MAIN_SERVER_H
#define DEFAULT_HOST "127.0.0.1"
#define DEFAULT_PORT 8080
#define DEFAULT_PROTOCOL 0
#define DEFAULT_DB_NAME "SERVER_PLATFORM_ON_C_CPP"
#define DEFAULT_DB_DIALECT "postgres"

#endif //SERVER_SIDE_PLATFORM_ON_C_CPP_MAIN_SERVER_H
